name: main-check
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repo
        uses: actions/checkout@v2
      - name: Run npm install
        run: make install
      - name: Run eslint linter
        run: make lint
      - name: Run jest tests
        run: make test
